Vagrant.configure(2) do |config|

config.vm.synced_folder "/Users/kyamada_macbookpro/work/mc2", "/vagrant", type:"virtualbox"
if Vagrant.has_plugin?("vagrant-timezone")
config.timezone.value = "Asia/Tokyo"

end

config.vm.define "node1" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "node1"
node.vm.network :private_network, ip: "192.168.40.10", virtualbox__intnet: "intnet"
end

config.vm.define "node2" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "node2"
node.vm.network :private_network, ip: "192.168.40.20", virtualbox__intnet: "intnet"
end

config.vm.define "node3" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "node3"
node.vm.network :private_network, ip: "192.168.40.30", virtualbox__intnet: "intnet"
end

config.vm.define "node4" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "node4"
node.vm.network :private_network, ip: "192.168.40.40", virtualbox__intnet: "intnet"
end

config.vm.define "node5" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "node5"
node.vm.network :private_network, ip: "192.168.40.50", virtualbox__intnet: "intnet"
end

config.vm.define "router1" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "router1"
node.vm.network :private_network, ip: "192.168.40.100", virtualbox__intnet: "intnet"
end

config.vm.define "router2" do |node|
node.vm.box = "centos/7"
node.vm.hostname = "router2"
node.vm.network :private_network, ip: "192.168.40.110", virtualbox__intnet: "intnet"
end

end